"""init

Revision ID: 84ee528a8eaa
Revises: 22be240460f8
Create Date: 2026-02-18 21:10:54.312441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84ee528a8eaa'
down_revision = '22be240460f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
